# Generated by Django 6.0.4 on 2026-04-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_usersite'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='content',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
